cargo-features = ["per-package-target"]

[package]
name = "component_example"
version = "0.1.0"
edition = "2021"

forced-target = "wasm32-unknown-unknown"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.26.0"