package test:guest;

interface foo {
    use bar.{host-resource};
    use-resource: func(a: borrow<host-resource>);
    consume-resource: func(a: host-resource);
}

interface bar {
    resource host-resource { 
        constructor(a: s32);
        print-a: func();
    }
}

world guest {
    export foo;
    import bar;
}